### ISSUE TITLE
Status unclear

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#136]
Bis heute habe ich 9 unterschiedliche Statusmeldungen kennengelernt.
Die Bedeutung ist unklar.
Ebenso, was bei jeweils sinnvoll zu tun wäre.

http://wiki.openseamap.org/wiki/OpenSeaMap-dev:De:Depth_upload#Liste_der_bisher_hochgeladenen_Dateien

**Comment by aAXEe** [comment]
Yes I agree that these messages are difficult to understand.
To get an impression about the different types I show all possible messages on my test system: http://osm.brasshack.de/#tracks
I think there is no good way to fix or improve this in the frontend. The backend sends this status information for each track decoded as a number. As the first step we should improve the wiki to make clear that each state is good for. Than we can improve the messages and the user interface.
Can somebody with knowledge of the backend provide some information about this?

**Comment by cleanerx** [comment]
This kind of work in progress as I keep adding states as required. Here is the current list.
I'm thinking of additional states for contour line generation but I'm not quite sure if this makes sense.
0 is upload incomplete - This state is valid when a track is started being uploaded and is set to
1 upload complete once the client notifies everything is fnished from the client side.
2 file corrupt is being set if the content detection failed or there is an error reading the file like a zip problem or something like that.
3 preprocessed is being set when the file format and contents could be sucessfully detected
4 file content unknown is not being used right now
5 file duplicate is being set when we figure another file that starts with the same exact 10 gps positions and time since this is highly unlikely that one will manage to do that during a recording.
6 file processed is being set when all trackpoints are processed and filtered
7 file no data is being set when the format was fine but the are no usable positions and depth data in the file. This may happen if someone uploads GPS only data that contains no depth data.
8 reprocess. This state is being set if I want to rerun a certain filter type and indicates that processed data from this track shall be discarded and reprocessed.

I think some tooltips over the states whould be really nice. What do you think ? 
Do you know a way for showing such a popup ? 
I wouldn't put it on the wiki because the user will look for it on the webpage.

**Comment by cleanerx** [comment]
Status is now available as tooltip
