### ISSUE TITLE
Neues Passwort eintragen

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#154]
Ein Datenspender sucht, wo man ein neues Passwort eintragen kann...

Bisher scheint diese Möglichkeit zu fehlen.
Wer sein Passwort verloren hat, kann nicht mehr mitmachen.

**Comment by aAXEe** [comment]
Heyho,
yep. There is no such code in the frontend. I do not know whether the backend has the captibility for this.

I think it is not too hard to implement this:
- Add a link to top menue ("Lost password" next to "Register"-Button)
- New page: Lost password
 - Form: EMail, Captcha
- OnSubmit: Send request to reset the passwort at the server
 - response: OK (mail sent to users mail address) / Error

From my point of view it should be possible to reuse the captcha code form the register page. But since I do not have the documentation or code for the backend I am not sure.

What do you think about this, Jens? Markus? Somebody else?
