### ISSUE TITLE
Login failed 2

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/depth_webfrontend#157]
Um eine Fehlermeldung eines Benutzers zu prüfen, startete ich http://depth.openseamap.org (Win8, FF).
Wenn ich als angemeldeter Benutzer auf "Tracks" klicke, 
erscheint das Fenster mit der Systemmeldung zum Einloggen.
Wenn ich dieses mit "Abbrechen" schliesse,
kann ich es mit einem weiteren Klick auf "Tracks" nicht mehr öffnen.

Damit es wieder erscheint, muss ich http://depth.openseamap.org neu laden...

**Comment by aAXEe** [comment]
Yes, that is a kind of feature of the backbone framework. It does not reload the page if the same url gets activated (that is happening with the click on the link).

Simple solution: click on another link and them come back to the tracks page

Real solutions:
1. make the link to the current page not click-able --> will force the user to reload or go to a different page
2. reload the current page than this link is clicked
3. add a reload button on the page

I would prefer solution 2 but it has side effects: All the information already entered in the form will be lost if the user clicks the link. Since this is the default behaviour on all websites I would accept that.

That do you think?

**Comment by Nautic** [comment]
Könnte man nicht das derzeitige Systemfenster für den Login durch ein Formular des Frameworks ersetzen?
Unabhängig von den Unterseiten Track, User und Ship.
Und damit obigen Fehler kontrollieren?
Hätte vermutlich auch den Vorteil, dass man den Login Benutzer-spezifisch gestalten könnte.

**Comment by cleanerx** [comment]
Duplicate https://github.com/OpenSeaMap/depth_webfrontend/issues/27
